### ISSUE TITLE
ctypes error when running sample code,python version is 3.6

### ISSUE THREAD

**Issue by pczzy** [niehusst/MapTextSynthesizer#16]
super@desk:/data0/project/MapTextSynthesizer/samples$ python text_synthesizer.py
Gtk-Message: 18:42:17.692: Failed to load module "canberra-gtk-module"
Traceback (most recent call last):
  File "text_synthesizer.py", line 110, in <module>
    guiLoop()
  File "text_synthesizer.py", line 68, in guiLoop
    caption,image = next( mts )
  File "../tensorflow/generator/data_synth.py", line 116, in data_generator
    yield next(iter)
  File "../tensorflow/generator/data_synth.py", line 102, in multithreaded_data_generator
    config_file_p = c.create_string_buffer(config_file)
  File "/data0/anaconda3/lib/python3.6/ctypes/__init__.py", line 63, in create_string_buffer
    raise TypeError(init)
TypeError: /data0/project/MapTextSynthesizer/samples/config.txt

**Comment by niehusst** [comment]
Did you change the config.txt settings or are you using the default settings that already existed in the file?
It seems like it ran into a problem while reading the settings from config.txt. Since we wrote the parser that pulls the info from the file from scratch, it is very finicky about newlines and characters that are out of place.

**Comment by pczzy** [comment]
it works when switch to python2.7 .
